---
title: "Modelo Herschel-Bulkley"
output: html_document
---

# Descrição 

  Este modelo é uma extensão do linear simples, pela adição da potência 
  de $\theta_{2}$, e é conhecido como modelo de Herschel-Bulkley. É uma
  função monótona e decrescente, com o formato:
  
  $$ f(x) = \theta_{0} + \theta_{1}x^{\theta_{2}}$$
  
  Onde:
  
  - $x \geq 0$,
  - $\theta_{0} (Y)$ é o intercepto da função,
  - $\theta_{1} \geq 0 (X^{-\theta_{2}})$ é a redução no intercepto
  quando $x = 1$, ou seja, $\theta_{1} = f(0) - f(1)$,
  - e $\theta_{2} > 0$ é o parâmetro que determina a concavidade - 
  se ele está entre 0 e 1, a função é côncava, se ele é maior que 1,
  é convexa e se o parâmetro é exatamente 1,  retorna-se ao modelo
  linear simples. 
  
## Aplicações

  Tensão de cisalhamento é um tipo de tensão gerado por forças aplicadas
  em sentidos iguais ou opostos, em direções semelhantes, mas com 
  intensidades diferentes no mesmo material analisado. Um exemplo é a 
  aplicação de forças paralelas mas em sentidos opostos, como em tesouras.
  Um fluido é uma substância que se deforma continuamente quando 
  submetida a uma tensão de cisalhamento, mesmo que ela seja muito pequena.
  
  O modelo de Herschel-Bulkley é bastante relacionado à mecânica de
  fluidos. Ele é uma equação generalizada de fluidos "Não Newtonianos",
  fluidos cuja tensão de cisalhamento não é diretamente proporcional
  a taxa de deformação, e podem não ter uma viscosidade bem definida. 
  Neste caso, modela-se é a quantidade média de força aplicada por 
  unidade de área (stress) no cisalhamento em função da taxa de 
  cisalhamento, e dos parâmetros, que significam:
  
  - $\theta_{0}$ o stress do "rendimento" do cisalhamento,
  - $\theta_{1}$ o índice de consistência do fluido, 
  - $\theta_{2}$ o índice do fluxo do fluido.
  
## Reparametrização
  
  Uma reparametrização proposta para este modelo inclui os 
  parâmetros $q$ e $\vartheta_{q}$, de forma que:
  
  - $q > 0 (Y)$ é uma constante que representa uma redução em $\theta_{0}$
  para a qual $\vartheta_{q} > 0 (X)$ é o valor correspondente na 
  abcissa, ou seja, $\theta_{0} - q = f(0) - f(\vartheta_{q})$. 
  
  A função agora toma a forma:
  
$$ f(x) = \theta_{0} + \theta_{1}x^
        {\frac{log(q)-log(\theta_{1})}{log(\vartheta_{q})}}$$


## Aplicações

  Esta reparametrização é útil ao considerarmos a modelagem de respostas
  assintóticas crescentes e decrescentes, a exemplo da produção em
  função de alguma condição não natural, como adubação, irrigação, ataque
  de pragas/doenças, ou até déficit hídrico. 