---
title: 'Modelo Logístico'
output: html_document
---

# Descrição

  O modelo Logístico é uma função sigmoidal e simétrica em relação ao 
  ponto de inflexão:
  
  $$ f(x) = \frac{\theta_{a}}{1+exp\{ \theta_{0} + \theta_{1}x \}}$$
  Onde:
  - $\theta_{a} \ (Y)$ é a assíntota superior do modelo,
  - $\theta_{0}$ e $\theta_{1} \ (X^{-1})$ não tem alguma interpretação
  direta.
  
## Aplicações

  Este modelo é utilizado em estudos de caso envolvendo, no geral, 
  curvas de crescimento individual, populacional (PINHEIRO; BATES, 2000;
  SCHABENBERGER; PIERCE, 2002) e o progresso de doenças (SEGARRA et. al.,
  2001). Diversas aplicações do modelo logístico seguindo abordagens
  parecidas são encontradas na literatura, como em questões sobre
  dose-resposta, bioensaios, inativação termal de botulina, modelagem
  de dados de crédito, etc. 

## Reparametrização
  
  O modelo reparametrizado tem a forma:
  
  $$ f(x) = \frac{\theta_{a}}{1+(\frac{q}{1-q}) exp\{-4 \vartheta_{t}
  (x - \vartheta_{q})\}}$$
  
  Assim, a taxa máxima de crescimento é representada por $\vartheta_{t}$
  **???** relativo a $\theta_{a}$. Ou seja, é a taxa máxima absoluta 
  $(Y\ X^{-1})$, dividida pela assíntota ou tamanho máximo $\theta_{a}$,
  e $\vartheta_{q} (X)$ é o tempo para alcançar uma fração $ 0 < q < 1$ 
  do tamanho final da função. 
  

  