---
title: "Modelo Mitscherlich"
output: html_document
---


# Descrição 
  
  O modelo Mitscherlich pode ser tratado como uma extensão do Exponencial
  assintótico. Esta extensão se dá com a adição do parâmetro $\theta_{0}$,
  com a função tomando a forma:
  
\[f(x) = \left\{
      \begin{array}{ll}
        \theta_{a}(1 - exp\{-\theta_{c}(x - \theta_{0})\}),\ x \geq \theta_{0} \\
        0, \ x < \theta_{0}
      \end{array}
\right. \]
    
    
  É uma função positiva, monótona crescente e côncava, sendo que:
    
  - $x \geq 0$,
  - $\theta_{a} > 0$ é a assíntota,
  - $\theta_{1} (X^{-1})$ está associado à taxa e
  - $\theta_{0} (X)$ o tempo de aquecimento, dado que a função é
    nula para $x < \theta_{0}$.
    
  Vale notar que esta função não possui ponto de inflexão, uma vez 
  que $f''(x) > 0$ não é satisfeito para nenhum valor de $x$. 
    
## Aplicações
    
  O modelo de Mitscherlich é frequentemente utilizado em diversas áreas 
  da biologia, química e agricultura, em situações onde é necessário 
  explicar um comportamento que se dá através de uma curva de 
  crescimento. Um exemplo é sua aplicação para descrever a resposta na 
  produção de cultivares à fertilização do solo com nutrientes. Para 
  isso, a pressuposição principal é a de que a taxa de aumento na 
  produção, por unidade de fertilizante, é proporcional à diferença 
  entre a produção esperada e a produção máxima. 
    
## Reparametrização

  Uma versão reparametrizada deste modelo é construída com introdução 
  da constante $q$, cujo domínio é entre $0$ e $1$. Ela representa uma 
  fração para a qual $\vartheta_{q} > 0 (X)$ é o valor correspondente
  na abcissa. ou seja, $\vartheta_{q}$ é o tempo para uma fração de vida
  $q$. A função reparametrizada assume a forma:
  
 $$f(x)  = \theta_{a} (1 - exp \{log(1-q)
                      (\frac{x-\theta_{0}}{\vartheta_{q} - \theta_{0}})\})$$
                      
                      
  Esta reparemetrização foi considerada por Peek et al. (2002) na 
  avaliação do acúmulo de $CO^{2}$ fotossintético, como função da
  intensidade luminosa em plantas de diferentes ambiente. Laureano, H. A.
  (2016), utilizou o mesmo modelo na estimação de diâmetros máximos e 
  seus tempos decorrentes em estudos de crescimento de lesão causada por
  fungos em frutos de maçã. 