---
title: "Polinômio de Segundo Grau"
output: html_document
---

# Descrição 

  O polinômio de segundo grau é um modelo linear nos parâmetros, também
  conhecido como modelo quadrático. A função do modelo pode assumir 
  diversas formas, dependendo dos valores dos parâmetros e possui 
  um ponto crítico, sendo simétrica em relação a ele:
  
  $$ f(x) = \theta_{0} + \theta_{1} x + \theta_{2} x^{2}$$
  
  - $\theta_{0}\ (Y)$ é o intercepto,
  - $\theta_{1}\ (Y\ X^{-1})$ é o coeficiente angular que representa
  a taxa na origem,
  -  $\theta_{2}\ (Y\ X^{-2})$ é representa a curvatura da função. 
  
  
## Aplicações

  O modelo foi aplicado por DALE, R. G., et. al. (2014), na avaliação de
  radioterapia fracionada quando ocorre recuperação incompleta normal de
  tecido entre as frações. BRENNER, D. J. (2008) também utilizou o modelo
  num contexto parecido, ou seja, na determinação de doses isoefetivas 
  em grandes doses por fração na radioterapia. Segundo ele, a ferramente
  mais utilizada na predição de dosagens/fracionamentos em radioterapia
  envolve modelos baseados no polinômio de segundo grau. 
  
## Reparametrização

  Na reparematrização deste modelo, a enfâse é no ponto crítico. Agora, 
  ele é representado de forma que $\vartheta_{y}\ (Y)$ é o valor no ponto
  crítico:
  
  $$ f(x) = \vartheta_{y} + \theta_{2}(x - \vartheta_{x})^{2}$$
  
  Este ponto é de máximo se $\theta_{2} < 0$ e mínimo se $\theta_{2} > 0$,
  correspondendo ao valor de $\vartheta_{y}\ (Y)$ na abcissa. O parâmetro
  $\theta_{2}$, por sua vez, mede a intensidade de mudança no valor da 
  função quando ela se afasta de $\vartheta_{x}$, podendo ser interpretado
  como um coeficiente de especificidade. 
  
## Aplicações

  Esta reparametrização foi considerada por Bullock e Bullock (1994)
  para avaliar níveis de adubação nitrogenada na cultura de milho. Além
  dessa aplicação, SERAFIM, et. al. (2012) utilizaram o modelo para
  verificar o efeito de doses de potássio na produtividade de soja em 
  associação à níveis de déficit hídrico. 