---
title: "Modelo Quadrático-Platô"
output: html_document
---

# Descrição 

  Este modelo segmentado é conhecido como modelo quadrático-platô, sendo
  a junção de uma reta horizontal com o ponto crítico do modelo 
  quadrático. A função do modelo pode ser crescente ou decrescente, na 
  porção representada pelo modelo quadrático, e constanto quando 
  $x > \theta_{b}$:
  
\[f(x) = \left\{
      \begin{array}{ll}
        \theta_{0} + \theta_{1} x + \theta_{2} x^{2},\ 
        x \geq \frac{-\theta_{1}}{2\theta_{2}} \\
        \theta_{0} + \theta_{1} (\frac{-\theta_{1}}{2\theta_{2}}) + 
        \theta_{2}(\frac{-\theta_{1}}{2\theta_{2}}),
        \ x > \frac{-\theta_{1}}{2\theta_{2}} \\
      \end{array}
\right. \]

  - $\theta_{0}\ (Y)$ é o intercepto,
  - $\theta_{1}\ (Y\ X^{-1})$ é o coeficiente angular que representa
  a taxa na origem,
  -  $\theta_{2}\ (Y\ X^{-2})$ é representa a curvatura da função. 
  
  A junção das duas funções é no ponto crítico do modelo quadrático, 
  calculado por $\frac{-\theta_{1}}{2\theta_{2}}$, que apresenta 
  derivada contínua. 
  
  
## Aplicações

  Esta classe de modelos foi estudada por BOCK, B. R., et. al. (1989),
  na avaliação da resposta de plantas à fertilizantes. Uma abordagem
  bem parecida é utilizada por ANDERSON, R. L, et. al. (1975), 
  contemplando outros modelos além do quadrático-platô. 


## Reparametrização

  A reparametrização deste modelo consiste na inclusão dos parâmetro 
  $\vartheta_{y}$ e $\vartheta_{x}$, que agora é o valor do ponto 
  crítico da função. Se $\theta_{2} > 0$ este ponto é de mínimo, e se 
  $\theta_{2} < 0$ ele é de máximo:

\[f(x) = \left\{
      \begin{array}{ll}
        \vartheta_{y} + \theta_{2} (x - \vartheta_{x})^{2},\ 
        x \geq \vartheta_{x} \\
        \vartheta_{y}, \ x > \vartheta_{x} \\
      \end{array}
\right. \]  
  
## Aplicações

  Para estudar o tamanho ótimo da parcela de avaliação da resistência do
  feijoeiro ao mofo branco, este modelo foi considerado por CARNEIRO et. al.
  (2011). Ainda, PEIXOTO et. al. (2011) utilizaram esta reparametrização
  no estudo da conservação *in vitro* de maracujazeiro. 